#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# mission-control desktop labels
yabai -m space 1 
yabai -m space 2
yabai -m space 3
yabai -m space 4
yabai -m space 5
yabai -m space 6
yabai -m space 7
yabai -m space 8 --label music
yabai -m space 9
yabai -m space 10

# window rules
# yabai -m rule --add app="^Mail$" space=mail
# yabai -m rule --add app="^Safari$" space=web
# yabai -m rule --add app="^Notes$" space=notes
# yabai -m rule --add app="^ida64$" space=re
# yabai -m rule --add app="^Transmission$" space=media
# yabai -m rule --add app="^Spotify$" space=media
# yabai -m rule --add app="^Discord$" space=social grid=1:1:0:0:1:1 manage=off
# yabai -m rule --add app="^Steam$" space=games manage=off
# yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off
# yabai -m rule --add app="^mpv$" manage=off border=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^日历$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^备忘录$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^计算器$" manage=off
yabai -m rule --add app="^Weather$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^QSpace Pro$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Photos$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Freeform$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Transmit$" manage=off
# 其他常用浮动应用
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^活动监视器$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^词典$" manage=off
yabai -m rule --add title="^About This Mac$" manage=off


yabai -m rule --add app="^Cisco Secure Client$" manage=off
yabai -m rule --add app="^TencentMeeting$" manage=off
yabai -m rule --add app="^Clash for Windows$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# yabai -m rule --add app="^NetEaseMusic$" space=music
yabai -m rule --add title="scratchpad" manage=off
yabai -m rule --add app="^D-Chat$" manage=off 
yabai -m rule --add app="^WeChat$" manage=off 

# specific space settings
yabai -m config --space mail  layout stack
yabai -m config --space games layout float

# global settings
yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         on           \
    focus_follows_mouse         autoraise    \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               off          \
    window_animation_duration   0.00         \
    window_opacity_duration     0.00         \
    active_window_opacity       1.00         \
    normal_window_opacity       0.85         \
    window_opacity              on           \
    insert_feedback_color       0xaad75f5f   \
    active_window_border_color  0xBF775759   \
    normal_window_border_color  0x7f353535   \
    window_border_width         4            \
    window_border_radius        12           \
    window_border_blur          off           \
    window_border_hidpi         on           \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 5           \
    left_padding                5           \
    right_padding               5           \
    bottom_padding              40           \
    window_gap                  10           \
    layout                      bsp          \
    mouse_modifier              cmd           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap

echo "yabai configuration loaded.."
